### ISSUE TITLE
Hello World Gives Authentication Error

### ISSUE THREAD

**Issue by mjallday** [1Password/onepassword-sdk-python#55]
I have a service account token. It works fine if I use the command line

```
op user get --me
ID:                     QQGG5YHCVNB7NIFXPQ4QUNPIYQ
Name:                   kopf
Email:                  ize73mcasdpou@1passwordserviceaccounts.com
State:                  ACTIVE
Type:                   SERVICE_ACCOUNT
Created:                4 hours ago
Updated:                4 hours ago
Last Authentication:    now
Expires:                19 hours from now
```

When I use the code from the sample

```python
#!/usr/bin/env python3
import asyncio
import os
from onepassword.client import Client


VAULT_ID = "XXXX"


async def main():
    # Gets your service account token from the OP_SERVICE_ACCOUNT_TOKEN environment variable.
    token = os.getenv("OP_SERVICE_ACCOUNT_TOKEN")
    print(token)

    # Connects to 1Password. Fill in your own integration name and version.
    client = await Client.authenticate(auth=token, integration_name="My 1Password Integration", integration_version="v1.0.0")

    # Retrieves a secret from 1Password. Takes a secret reference as input and returns the secret to which it points.
    value = await client.secrets.resolve(f"op://{VAULT_ID}/KOPF/GITHUB_PAT")
    # use value here
    print(value)


if __name__ == '__main__':
    asyncio.run(main())
```

However when I invoke this I get an error

```
Traceback (most recent call last):
  File "/Users/marshall/code/vgs/configurations/./ops/bootstrap-secrets", line 25, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/marshall/code/vgs/configurations/./ops/bootstrap-secrets", line 16, in main
    client = await Client.authenticate(auth=token, integration_name="My 1Password Integration", integration_version="v1.0.0")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marshall/code/vgs/configurations/path/to/venv/lib/python3.12/site-packages/onepassword/client.py", line 18, in authenticate
    client_id = int(await _init_client(self.config))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marshall/code/vgs/configurations/path/to/venv/lib/python3.12/site-packages/onepassword/core.py", line 19, in _init_client
    return await core.init_client(json.dumps(client_config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marshall/code/vgs/configurations/path/to/venv/lib/python3.12/site-packages/onepassword/lib/aarch64/op_uniffi_core.py", line 822, in _uniffi_rust_call_async
    _rust_call_with_error(error_ffi_converter, ffi_complete, rust_future)
  File "/Users/marshall/code/vgs/configurations/path/to/venv/lib/python3.12/site-packages/onepassword/lib/aarch64/op_uniffi_core.py", line 286, in _rust_call_with_error
    _uniffi_check_call_status(error_ffi_converter, call_status)
  File "/Users/marshall/code/vgs/configurations/path/to/venv/lib/python3.12/site-packages/onepassword/lib/aarch64/op_uniffi_core.py", line 297, in _uniffi_check_call_status
    raise error_ffi_converter.lift(call_status.error_buf)
onepassword.lib.aarch64.op_uniffi_core.Error.Error: msg='invalid service account token, please make sure you provide a valid service account token as parameter: service account deserialization failed'
```

Is this related to the codebase? I installed it using 

```bash
pip3 install git+ssh://git@github.com/1Password/onepassword-sdk-python.git@v0.1.0-beta.11
```

**Comment by AndyTitu** [comment]
@mjallday The main error seems to be: `invalid service account token, please make sure you provide a valid service account token as parameter: service account deserialization failed'` You probably need to provide a correct token.

**Comment by mjallday** [comment]
Seems like a reasonable assumption. It might not be clear but in the issue I document I can call `op user get --me` and it is executing fine. 

<img width="1423" alt="image" src="https://github.com/1Password/onepassword-sdk-python/assets/252280/86f84d5d-cd8c-48d8-9bce-305718034b5b">

I stepped into the auth method but it looks like it's shelling out to some rust function and my debugger will not step into that. 

Here's another example, you can see i'm creating the token and then calling cli first (successfully) and then using the python code (unsuccessful)

<img width="1415" alt="image" src="https://github.com/1Password/onepassword-sdk-python/assets/252280/7ec2b550-b101-4a9a-b417-39482a8845b7">

My virtual env looks like this

```
annotated-types==0.7.0
anyio==4.4.0
certifi==2024.6.2
h11==0.14.0
httpcore==0.16.3
httpx==0.23.3
idna==3.7
onepassword @ git+ssh://git@github.com/1Password/onepassword-sdk-python.git@5b0adda3d1b5608232a8d640dc01a60dda676350
onepasswordconnectsdk==1.5.1
pydantic==2.7.4
pydantic_core==2.18.4
python-dateutil==2.9.0.post0
rfc3986==1.5.0
six==1.16.0
sniffio==1.3.1
typing_extensions==4.12.2
```

```
python3 -V
Python 3.12.3
```

```
uname -a
Darwin marshall-C23JNQ421P 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

**Comment by MOmarMiraj** [comment]
@mjallday Thanks for bringing up this issue, just wanted to ask a couple of questions to get more details about your issue. 

One quick note,  looking at your venv requirements.txt, looks like you have beta.9 installed in ur venv as per commit SHA but in the original ticket, you said you installed beta.11. Could you verify the SDK version you are on? and if your on beta.9 could you update to the latest.

Could you also provide us with more details about your current setup? The steps you are performing before running into this error, how you generate the service account token, and anything else you think is significant.

Thanks!

**Comment by mjallday** [comment]
I tried a new venv to solve for that and then removed the venv to try and simplify the setup. 

Here's the build output

`pip3 install git+ssh://git@github.com/1Password/onepassword-sdk-python.git@v0.1.0-beta.11`
```
Defaulting to user installation because normal site-packages is not writeable
Collecting git+ssh://****@github.com/1Password/onepassword-sdk-python.git@v0.1.0-beta.11
  Cloning ssh://****@github.com/1Password/onepassword-sdk-python.git (to revision v0.1.0-beta.11) to /private/var/folders/jc/wczpcxss48q4b7s4lth3wy2r0000gn/T/pip-req-build-z_2h6n36
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/1Password/onepassword-sdk-python.git' /private/var/folders/jc/wczpcxss48q4b7s4lth3wy2r0000gn/T/pip-req-build-z_2h6n36
  Running command git checkout -q 30257cb1643112efb956dd5236869ca0623f01f0
  Resolved ssh://****@github.com/1Password/onepassword-sdk-python.git to commit 30257cb1643112efb956dd5236869ca0623f01f0
  Preparing metadata (setup.py) ... done
Collecting pydantic (from onepassword==0.1.0b10)
  Using cached pydantic-2.7.4-py3-none-any.whl.metadata (109 kB)
Collecting annotated-types>=0.4.0 (from pydantic->onepassword==0.1.0b10)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.18.4 (from pydantic->onepassword==0.1.0b10)
  Downloading pydantic_core-2.18.4-cp39-cp39-macosx_11_0_arm64.whl.metadata (6.5 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/marshall/Library/Python/3.9/lib/python/site-packages (from pydantic->onepassword==0.1.0b10) (4.11.0)
Using cached pydantic-2.7.4-py3-none-any.whl (409 kB)
Downloading pydantic_core-2.18.4-cp39-cp39-macosx_11_0_arm64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 3.5 MB/s eta 0:00:00                                                                                                                                                                                    Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)                                                                                                                                                                                                    Building wheels for collected packages: onepassword                                                                                                                                                                                                              Building wheel for onepassword (setup.py) ... done
  Created wheel for onepassword: filename=onepassword-0.1.0b10-cp39-cp39-macosx_14_0_universal2.whl size=2951980 sha256=042f4221685ea3a65464b03ce1d428f9d77f14bfce6c052776fcc1e33c23c653
  Stored in directory: /private/var/folders/jc/wczpcxss48q4b7s4lth3wy2r0000gn/T/pip-ephem-wheel-cache-eaipinlw/wheels/00/b1/ad/ff2e06e78b80514e3c432bfb0c42ca722b80ce609142beeb34
Successfully built onepassword
Installing collected packages: pydantic-core, annotated-types, pydantic, onepassword
Successfully installed annotated-types-0.7.0 onepassword-0.1.0b10 pydantic-2.7.4 pydantic-core-2.18.4
```

and then 

```
Traceback (most recent call last):
  File "/Users/marshall/code/vgs/configurations/./ops/bootstrap-secrets", line 24, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/marshall/code/vgs/configurations/./ops/bootstrap-secrets", line 15, in main
    client = await Client.authenticate(auth=token, integration_name="My 1Password Integration", integration_version="v1.0.0")
  File "/Users/marshall/Library/Python/3.9/lib/python/site-packages/onepassword/client.py", line 21, in authenticate
    client_id = int(await _init_client(config))
  File "/Users/marshall/Library/Python/3.9/lib/python/site-packages/onepassword/core.py", line 17, in _init_client
    return await core.init_client(json.dumps(client_config))
  File "/Users/marshall/Library/Python/3.9/lib/python/site-packages/onepassword/lib/aarch64/op_uniffi_core.py", line 822, in _uniffi_rust_call_async
    _rust_call_with_error(error_ffi_converter, ffi_complete, rust_future)
  File "/Users/marshall/Library/Python/3.9/lib/python/site-packages/onepassword/lib/aarch64/op_uniffi_core.py", line 286, in _rust_call_with_error
    _uniffi_check_call_status(error_ffi_converter, call_status)
  File "/Users/marshall/Library/Python/3.9/lib/python/site-packages/onepassword/lib/aarch64/op_uniffi_core.py", line 297, in _uniffi_check_call_status
    raise error_ffi_converter.lift(call_status.error_buf)
onepassword.lib.aarch64.op_uniffi_core.Error: msg='invalid service account token, please make sure you provide a valid service account token as parameter: service account deserialization failed'
```

I've generated a new service account credential and confirmed it works from the cli. Currently as a workaround I'm shelling out to the 1password cli so I'm not blocked but definitely feels like the library has an auth issue. 

```
python3 -V
Python 3.9.6
```

this is on a relatively clean mbp running sonoma. in the venv i had a newer version of python (Python 3.12.4)

i can try running in a docker container if you think that'll aid debugging.

> Could you also provide us with more details about your current setup? The steps you are performing before running into this error, how you generate the service account token, and anything else you think is significant.

`op service-account create kopf --expires-in 1d --vault fcet2bp7u6ajylnpik7ifb7pli:read_items,write_items` is the command i'm using

**Comment by MOmarMiraj** [comment]
@mjallday Thanks for providing the necessary information, indeed it is a bug when creating a service account token using the CLI, it doesn't correctly parse the service account token. I will raise an internal issue and will let you know as soon as this gets addressed.

In the meantime, a workaround is creating a service account token through the website. You can find more information on how to do that [here](https://developer.1password.com/docs/service-accounts/get-started/)

**Comment by MOmarMiraj** [comment]
Hey @mjallday.. With the v0.1.0-beta.13 release of the Python SDK, This bug should be fixed and the CLI Service Tokens should not error out anymore. If you have any more troubles with this... please feel free to open a new thread.
