### ISSUE TITLE
pip install fails with "Preparing metadata (pyproject.toml) ... error"

### ISSUE THREAD

**Issue by svenXY** [1Password/onepassword-sdk-python#62]
I'm trying
`pip install git+ssh://git@github.com/1Password/onepassword-sdk-python.git@v0.1.0-beta.9`
on an M1 Macbook with python 3.12.2 and cannot successfully install the sdk:

```
Collecting git+ssh://****@github.com/1Password/onepassword-sdk-python.git@v0.1.0-beta.9
  Cloning ssh://****@github.com/1Password/onepassword-sdk-python.git (to revision v0.1.0-beta.9) to /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-req-build-fmbdb_gb
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/1Password/onepassword-sdk-python.git' /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-req-build-fmbdb_gb
  Running command git checkout -q ef3cc81a35d9414c64b74b894d9bad21bfe291a1
  Resolved ssh://****@github.com/1Password/onepassword-sdk-python.git to commit ef3cc81a35d9414c64b74b894d9bad21bfe291a1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/dist.py:318: InformationOnly: Normalizing '0.1.0-beta.1' to '0.1.0b1'
        self.metadata.version = self._normalize_version(self.metadata.version)
      running dist_info
      creating /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info
      writing /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info/requires.txt
      writing top-level names to /private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info/top_level.txt
      writing manifest file '/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword.egg-info/SOURCES.txt'
      creating '/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-modern-metadata-55c47ila/onepassword-0.1.0b1.dist-info'
      Traceback (most recent call last):
        File "/Users/Sven.Hergenhahn/gitlab-dm/gitlab-utils/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/Sven.Hergenhahn/gitlab-dm/gitlab-utils/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/Sven.Hergenhahn/gitlab-dm/gitlab-utils/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 46, in <module>
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/command/dist_info.py", line 97, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 302, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zw/j4_3jg_57110p8fj7r1g5shc0000gq/T/pip-build-env-lky9xjwv/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 863, in get_command_obj
          cmd_obj = self.command_obj[command] = klass(self)
                                                ^^^^^^^^^^^
      TypeError: 'NoneType' object is not callable
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

Do you have any advice for me on how to proceed from here?

Thanks,
Sven

**Comment by svenXY** [comment]
never mind - I ran `pip install --upgrade pip wheel setuptools` and it worked
